version: 1
formatters:
  standard:
    format: "[%(asctime)s] %(levelname)s %(name)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
loggers:
  lic_sales_agent:
    level: INFO
    handlers: [console]
    propagate: False
root:
  level: INFO
  handlers: [console]

